### ISSUE TITLE
Failed at the cdk-sample@0.1.0 build script

### ISSUE THREAD

**Issue by hopewise** [awslabs/aws-rails-provisioner#11]
I have an issue when try to build:
```
$ aws-rails-provisioner build                                                                                                                                                                                          
replacing cdk-sample/lib/cdk-sample-init-stack.ts
replacing cdk-sample/lib/aws-rails-provisioner-fargate-stack.ts
replacing cdk-sample/bin/cdk-sample.ts
npm WARN cdk-sample@0.1.0 No repository field.
npm WARN cdk-sample@0.1.0 No license field.

npm WARN cdk-sample@0.1.0 No repository field.
npm WARN cdk-sample@0.1.0 No license field.

npm WARN cdk-sample@0.1.0 No repository field.
npm WARN cdk-sample@0.1.0 No license field.

npm WARN cdk-sample@0.1.0 No repository field.
npm WARN cdk-sample@0.1.0 No license field.

npm WARN cdk-sample@0.1.0 No repository field.
npm WARN cdk-sample@0.1.0 No license field.

npm WARN cdk-sample@0.1.0 No repository field.
npm WARN cdk-sample@0.1.0 No license field.

running npm run build ...

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! cdk-sample@0.1.0 build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the cdk-sample@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/samir/.npm/_logs/2020-02-05T11_24_57_799Z-debug.log
```
the log file:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/12.12.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.11.3
3 info using node@v12.12.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle cdk-sample@0.1.0~prebuild: cdk-sample@0.1.0
6 info lifecycle cdk-sample@0.1.0~build: cdk-sample@0.1.0
7 verbose lifecycle cdk-sample@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle cdk-sample@0.1.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/samir/Documents/projects/cdk-sample/node_modules/.bin:/Users/samir/.rvm/gems/ruby-2.7.0/bin:/Users/samir/.rvm/gems/ruby-2.7.0@global/bin:/Users/samir/.rvm/rubies/ruby-2.7.0/bin:/Users/samir/.rvm/bin:/usr/local/opt/dart@1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/samir/Library/Android/sdk/platform-tools
9 verbose lifecycle cdk-sample@0.1.0~build: CWD: /Users/samir/Documents/projects/cdk-sample
10 silly lifecycle cdk-sample@0.1.0~build: Args: [ '-c', 'tsc' ]
11 silly lifecycle cdk-sample@0.1.0~build: Returned: code: 2  signal: null
12 info lifecycle cdk-sample@0.1.0~build: Failed to exec build script
13 verbose stack Error: cdk-sample@0.1.0 build: `tsc`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid cdk-sample@0.1.0
15 verbose cwd /Users/samir/Documents/projects/cdk-sample
16 verbose Darwin 19.2.0
17 verbose argv "/usr/local/Cellar/node/12.12.0/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v12.12.0
19 verbose npm  v6.11.3
20 error code ELIFECYCLE
21 error errno 2
22 error cdk-sample@0.1.0 build: `tsc`
22 error Exit status 2
23 error Failed at the cdk-sample@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```
settings file:

```
  1 version: "0"
  2 services: 
  3   aws-rails-provisioner:
  4     source_path: ./docker-test
  5     fargate: 
  6       desired_count: 3
  7       envs: 
  8         AWS_FARGATE_ENV_VAR: "Passed By aws-rails-provisioner"
  9         PORT: 80
 10         RAILS_LOG_TO_STDOUT: true
 11       public: true
 12 vpc:  
 13   cidr: 10.0.0.0/21
 14   enable_dns: true
 15   max_azs: 2

```

**Comment by alkami-io** [comment]
were you able to get past this, I'm currently stuck at the same place.

**Comment by mullermp** [comment]
Hey - I'm sorry this is very late here; we've been short on hands the last 6 months. I've started picking up these issues. I wasn't the original author of this code but I have been working through it to understand it better. Did you use `--with-cicd` at some point? I ran into this same issue but was able to get past it without providing that flag. I had to scrap the cdk-sample directory and the package lock file to try again. I will investigate this.

**Comment by bunnrf** [comment]
Just ran into this too. 

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/x/.nvm/versions/node/v10.16.0/bin/node',
1 verbose cli   '/Users/x/.nvm/versions/node/v10.16.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   '--verbose' ]
2 info using npm@6.14.5
3 info using node@v10.16.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle cdk-sample@0.1.0~prebuild: cdk-sample@0.1.0
6 info lifecycle cdk-sample@0.1.0~build: cdk-sample@0.1.0
7 verbose lifecycle cdk-sample@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle cdk-sample@0.1.0~build: PATH: /Users/x/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/x/cdk-sample/node_modules/.bin:/Users/x/.nvm/versions/node/v10.16.0/bin:/Users/x/.rvm/gems/ruby-2.6.3/bin:/Users/x/.rvm/gems/ruby-2.6.3@global/bin:/Users/x/.rvm/rubies/ruby-2.6.3/bin:/Users/x/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Apple/bin
9 verbose lifecycle cdk-sample@0.1.0~build: CWD: /Users/x/cdk-sample
10 silly lifecycle cdk-sample@0.1.0~build: Args: [ '-c', 'tsc' ]
11 silly lifecycle cdk-sample@0.1.0~build: Returned: code: 2  signal: null
12 info lifecycle cdk-sample@0.1.0~build: Failed to exec build script
13 verbose stack Error: cdk-sample@0.1.0 build: `tsc`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/Users/x/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/x/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid cdk-sample@0.1.0
15 verbose cwd /Users/x/cdk-sample
16 verbose Darwin 19.0.0
17 verbose argv "/Users/x/.nvm/versions/node/v10.16.0/bin/node" "/Users/x/.nvm/versions/node/v10.16.0/bin/npm" "run" "build" "--verbose"
18 verbose node v10.16.0
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 2
22 error cdk-sample@0.1.0 build: `tsc`
22 error Exit status 2
23 error Failed at the cdk-sample@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

Running `tsc` in the cdk-sample dir gives more details. In my case, I had copied the db backup options from [the docs](https://docs.aws.amazon.com/awsrailsprovisioner/api/Aws/RailsProvisioner/DBCluster.html) which don't line up with the props in the cdk:
```
lib/web-fargate-stack.ts:54:17 - error TS2322: Type '{ retentionDays: number; preferred_window: string; }' is not assignable to type 'BackupProps'.
  Object literal may only specify known properties, and 'retentionDays' does not exist in type 'BackupProps'.

54                 retentionDays: 7,
                   ~~~~~~~~~~~~~~~~

  node_modules/@aws-cdk/aws-rds/lib/cluster.d.ts:49:14
    49     readonly backup?: BackupProps;
                    ~~~~~~
    The expected type comes from property 'backup' which is declared here on type 'DatabaseClusterProps'


Found 1 error.
```
```
node_modules/@aws-cdk/aws-rds/lib/cluster.d.ts

export interface BackupProps {
    /**
     * How many days to retain the backup
     */
    readonly retention: Duration;
    /**
     * A daily time range in 24-hours UTC format in which backups preferably execute.
     *
     * Must be at least 30 minutes long.
     *
     * Example: '01:00-02:00'
     *
     * @default - a 30-minute window selected at random from an 8-hour block of
     * time for each AWS Region. To see the time blocks available, see
     * https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithAutomatedBackups.html#USER_WorkingWithAutomatedBackups.BackupWindow
     */
    readonly preferredWindow?: string;
}
```

Wasn't able to work around it so I just removed the backup config and the build succeeded.

OP's issue may have a different cause but if anyone else encounters this the `tsc` trick will probably give more info.
