### ISSUE TITLE
Numerous file errors upon build

### ISSUE THREAD

**Issue by artzte** [awslabs/aws-rails-provisioner#16]
I added a cdk_dir option to my aws-rails-provisioner.yml file after encountering errors about a missing cdk-sample directory.

I am now getting errors about a missing cdk file or directory.

Is there a particular directory tree that this tool expects, perhaps relative to the location of the aws-rails-provisioner.yml?

````
➜  api git:(develop) ✗ aws-rails-provisioner build                      
Traceback (most recent call last):
	7: from /home/eric/.rbenv/versions/2.6.6/bin/aws-rails-provisioner:23:in `<main>'
	6: from /home/eric/.rbenv/versions/2.6.6/bin/aws-rails-provisioner:23:in `load'
	5: from /home/eric/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/aws-rails-provisioner-0.0.2.rc3/bin/aws-rails-provisioner:119:in `<top (required)>'
	4: from /home/eric/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/aws-rails-provisioner-0.0.2.rc3/lib/aws-rails-provisioner/cdk_builder.rb:13:in `run'
	3: from /home/eric/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/aws-rails-provisioner-0.0.2.rc3/lib/aws-rails-provisioner/cdk_builder.rb:37:in `_init_cdk'
	2: from /home/eric/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/aws-rails-provisioner-0.0.2.rc3/lib/aws-rails-provisioner/cdk_builder.rb:37:in `chdir'
	1: from /home/eric/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/aws-rails-provisioner-0.0.2.rc3/lib/aws-rails-provisioner/cdk_builder.rb:39:in `block in _init_cdk'
/home/eric/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/aws-rails-provisioner-0.0.2.rc3/lib/aws-rails-provisioner/cdk_builder.rb:39:in ``': No such file or directory - cdk (Errno::ENOENT)

**Comment by artzte** [comment]
nmd had not installed aws-cdk
