### ISSUE TITLE
NPM build failed

### ISSUE THREAD

**Issue by bismark64** [awslabs/aws-rails-provisioner#18]
This is a great gem but when trying to run the build command, I'm getting this error on my machine:

`
Executing npm install...
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN cdk-sample@0.1.0 No repository field.
npm WARN cdk-sample@0.1.0 No license field.

✅ All done!
creating cdk-sample/lib/cdk-sample-init-stack.ts
creating cdk-sample/lib/vthere-fargate-stack.ts
replacing cdk-sample/bin/cdk-sample.ts
installing pkg: @aws-cdk/aws-ec2 ...
npm WARN cdk-sample@0.1.0 No repository field.
npm WARN cdk-sample@0.1.0 No license field.

installing pkg: @aws-cdk/aws-ecs ...
npm WARN cdk-sample@0.1.0 No repository field.
npm WARN cdk-sample@0.1.0 No license field.

installing pkg: @aws-cdk/aws-ecs-patterns ...
npm WARN cdk-sample@0.1.0 No repository field.
npm WARN cdk-sample@0.1.0 No license field.

installing pkg: @aws-cdk/aws-ecr-assets ...
npm WARN cdk-sample@0.1.0 No repository field.
npm WARN cdk-sample@0.1.0 No license field.

installing pkg: @aws-cdk/aws-rds ...
npm WARN cdk-sample@0.1.0 No repository field.
npm WARN cdk-sample@0.1.0 No license field.

installing pkg: @aws-cdk/aws-certificatemanager ...
npm WARN cdk-sample@0.1.0 No repository field.
npm WARN cdk-sample@0.1.0 No license field.

installing pkg: @aws-cdk/aws-secretsmanager ...
npm WARN cdk-sample@0.1.0 No repository field.
npm WARN cdk-sample@0.1.0 No license field.

running npm run build ...
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/usr/local/Cellar/node/14.11.0/bin/node',
npm verb cli   '/Users/bismark/.npm-global/bin/npm',
npm verb cli   'run',
npm verb cli   'build',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@6.14.8
npm info using node@v14.11.0
npm verb run-script [ 'prebuild', 'build', 'postbuild' ]
npm info lifecycle cdk-sample@0.1.0~prebuild: cdk-sample@0.1.0
npm info lifecycle cdk-sample@0.1.0~build: cdk-sample@0.1.0
npm verb lifecycle cdk-sample@0.1.0~build: unsafe-perm in lifecycle true
npm verb lifecycle cdk-sample@0.1.0~build: CWD: /Users/bismark/Documents/rails/vthere/cdk-sample
npm info lifecycle cdk-sample@0.1.0~build: Failed to exec build script
npm verb stack Error: cdk-sample@0.1.0 build: `tsc`
npm verb stack Exit status 2
npm verb stack     at EventEmitter.<anonymous> (/Users/bismark/.npm-global/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:314:20)
npm verb stack     at ChildProcess.<anonymous> (/Users/bismark/.npm-global/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:314:20)
npm verb stack     at maybeClose (internal/child_process.js:1047:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
npm verb pkgid cdk-sample@0.1.0
npm verb cwd /Users/bismark/Documents/rails/vthere/cdk-sample
npm verb Darwin 19.6.0
npm verb argv "/usr/local/Cellar/node/14.11.0/bin/node" "/Users/bismark/.npm-global/bin/npm" "run" "build" "--verbose"
npm verb node v14.11.0
npm verb npm  v6.14.8
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! cdk-sample@0.1.0 build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the cdk-sample@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 2, true ]
npm timing npm Completed in 5191ms`

Any ideas why is this happening?

**Comment by mullermp** [comment]
Hey @bismark64, CDK (unlike SDK) makes breaking changes. It's possible that it has happened here. Could you try running `tsc` (from your node_modules path) on your cdk-sample directory directly and see what javascript errors exist?

**Comment by bismark64** [comment]
After following your advice running `tsc` directly I found the issue is related to a mismatch on the expected type for `domainZone`:

```
lib/vthere-fargate-stack.ts:95:13 - error TS2322: Type 'string' is not assignable to type 'IHostedZone | undefined'.

95             domainZone: 'example.com',
               ~~~~~~~~~~
```
Is it absolutely necessary to include this field? I've specified a `domain_name` in the aws-rails-provisioner.yml file as well.

**Comment by mullermp** [comment]
Domain name appears to be used right above domain zone: https://github.com/awslabs/aws-rails-provisioner/blob/6567d128235f26c1c81c92113f07dfdf41600ee8/templates/fargate_stack.mustache#L138-L140

Are you defining domain zone in your YAML configuration? If not you can probably leave it out. AFAIK configuration is only used for generating the relevant typescript CDK code.

It seems that `domainZone` used to take a string but now takes a type `IHostedZone` (https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-route53.IHostedZone.html). I suppose that this object can be constructed and passed "example.com" as "zoneName" for `IHostedZone`.

**Comment by bismark64** [comment]
Yes I'm defining a domain zone, if I remove it from the YAML file it works fine.

In case anyone else is having this issue I just replaced: 

`domainZone: 'example.com',` to 

`domainZone: route53.HostedZone.fromLookup(this, 'DomainZone', { domainName: 'example.com' }),` 
or
`domainZone: route53.HostedZone.fromHostedZoneAttributes(this, 'DomainZone', { zoneName: 'example.com', hostedZoneId: 'ZXXXXXXXXXXX' }),`

which they both return a `IHostedZone` type, and then run `tsc` again with no issues.

**Comment by mullermp** [comment]
Awesome. Happy to take a pull request if you want to contribute a fix back :)

**Comment by chrisgeek** [comment]
I am currently facing the same problem,
aws-rails-provisioner returns
```
Applying project template app for typescript
# Welcome to your CDK TypeScript project!

This is a blank project for TypeScript development with CDK.

The `cdk.json` file tells the CDK Toolkit how to execute your app.

## Useful commands

 * `npm run build`   compile typescript to js
 * `npm run watch`   watch for changes and compile
 * `npm run test`    perform the jest unit tests
 * `cdk deploy`      deploy this stack to your default AWS account/region
 * `cdk diff`        compare deployed stack with current state
 * `cdk synth`       emits the synthesized CloudFormation template

Executing npm install...
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.2.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN cdk-sample@0.1.0 No repository field.
npm WARN cdk-sample@0.1.0 No license field.

✅ All done!
creating cdk-sample/lib/cdk-sample-init-stack.ts
creating cdk-sample/lib/hospital-sys-fargate-stack.ts
replacing cdk-sample/bin/cdk-sample.ts
installing pkg: @aws-cdk/aws-ec2 ...
npm WARN cdk-sample@0.1.0 No repository field.
npm WARN cdk-sample@0.1.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.2.1 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.2.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

installing pkg: @aws-cdk/aws-ecs ...
npm WARN cdk-sample@0.1.0 No repository field.
npm WARN cdk-sample@0.1.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.2.1 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.2.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

installing pkg: @aws-cdk/aws-ecs-patterns ...
npm WARN cdk-sample@0.1.0 No repository field.
npm WARN cdk-sample@0.1.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.2.1 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.2.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

installing pkg: @aws-cdk/aws-ecr-assets ...
npm WARN cdk-sample@0.1.0 No repository field.
npm WARN cdk-sample@0.1.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.2.1 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.2.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

installing pkg: @aws-cdk/aws-rds ...
npm WARN cdk-sample@0.1.0 No repository field.
npm WARN cdk-sample@0.1.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.2.1 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.2.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

installing pkg: @aws-cdk/aws-secretsmanager ...
npm WARN cdk-sample@0.1.0 No repository field.
npm WARN cdk-sample@0.1.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.2.1 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.2.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

running npm run build ...
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build', '--verbose' ]
npm info using npm@6.14.6
npm info using node@v10.22.1
npm verb run-script [ 'prebuild', 'build', 'postbuild' ]
npm info lifecycle cdk-sample@0.1.0~prebuild: cdk-sample@0.1.0
npm info lifecycle cdk-sample@0.1.0~build: cdk-sample@0.1.0
npm verb lifecycle cdk-sample@0.1.0~build: unsafe-perm in lifecycle true
npm verb lifecycle cdk-sample@0.1.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/chrisgeek/Documents/RailsProjects/hospital-sys/cdk-sample/node_modules/.bin:/home/chrisgeek/.rbenv/versions/2.5.1/bin:/home/chrisgeek/.rbenv/libexec:/home/chrisgeek/.rbenv/plugins/ruby-build/bin:/home/chrisgeek/.yarn/bin:/home/chrisgeek/.config/yarn/global/node_modules/.bin:/home/chrisgeek/.rbenv/plugins/ruby-build/bin:/home/chrisgeek/.rbenv/shims:/home/chrisgeek/.rbenv/bin:/home/chrisgeek/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
npm verb lifecycle cdk-sample@0.1.0~build: CWD: /home/chrisgeek/Documents/RailsProjects/hospital-sys/cdk-sample
npm info lifecycle cdk-sample@0.1.0~build: Failed to exec build script
npm verb stack Error: cdk-sample@0.1.0 build: `tsc`
npm verb stack Exit status 2
npm verb stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:198:13)
npm verb stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:198:13)
npm verb stack     at maybeClose (internal/child_process.js:982:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
npm verb pkgid cdk-sample@0.1.0
npm verb cwd /home/chrisgeek/Documents/RailsProjects/hospital-sys/cdk-sample
npm verb Linux 4.15.0-122-generic
npm verb argv "/usr/bin/node" "/usr/bin/npm" "run" "build" "--verbose"
npm verb node v10.22.1
npm verb npm  v6.14.6
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! cdk-sample@0.1.0 build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the cdk-sample@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 2, true ]
npm timing npm Completed in 28485ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/chrisgeek/.npm/_logs/2020-11-22T09_00_42_235Z-debug.log

``````
 when I run `tsc` I get the errors below
```
../bin/cdk-sample.ts:5:18 - error TS1005: ',' expected.

5 import { Hospital-sysFargateStack } from '../lib/hospital-sys-fargate-stack';
                   ~

../bin/cdk-sample.ts:5:35 - error TS1128: Declaration or statement expected.

5 import { Hospital-sysFargateStack } from '../lib/hospital-sys-fargate-stack';
                                    ~

../bin/cdk-sample.ts:5:42 - error TS1005: ';' expected.

5 import { Hospital-sysFargateStack } from '../lib/hospital-sys-fargate-stack';
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../lib/hospital-sys-fargate-stack.ts:9:19 - error TS1005: '{' expected.

9 interface Hospital-sysFargateStackProps {
                    ~

../lib/hospital-sys-fargate-stack.ts:9:41 - error TS1005: ';' expected.

9 interface Hospital-sysFargateStackProps {
                                          ~

../lib/hospital-sys-fargate-stack.ts:11:12 - error TS1005: ';' expected.

11     cluster: ecs.ICluster,
              ~

../lib/hospital-sys-fargate-stack.ts:12:1 - error TS1109: Expression expected.

12 }
   ~

../lib/hospital-sys-fargate-stack.ts:14:22 - error TS1005: '{' expected.

14 export class Hospital-sysFargateStack extends cdk.Stack {
                        ~

../lib/hospital-sys-fargate-stack.ts:14:39 - error TS1005: ';' expected.

14 export class Hospital-sysFargateStack extends cdk.Stack {
                                         ~~~~~~~

../lib/hospital-sys-fargate-stack.ts:14:57 - error TS1005: ';' expected.

14 export class Hospital-sysFargateStack extends cdk.Stack {
                                                           ~

../lib/hospital-sys-fargate-stack.ts:15:5 - error TS1128: Declaration or statement expected.

15     public readonly service: ecs.FargateService;
       ~~~~~~

../lib/hospital-sys-fargate-stack.ts:15:12 - error TS1128: Declaration or statement expected.

15     public readonly service: ecs.FargateService;
              ~~~~~~~~

../lib/hospital-sys-fargate-stack.ts:16:5 - error TS1128: Declaration or statement expected.

16     public readonly repoName: string;
       ~~~~~~

../lib/hospital-sys-fargate-stack.ts:16:12 - error TS1128: Declaration or statement expected.

16     public readonly repoName: string;
              ~~~~~~~~

../lib/hospital-sys-fargate-stack.ts:17:5 - error TS1128: Declaration or statement expected.

17     public readonly dbUrl: string;
       ~~~~~~

../lib/hospital-sys-fargate-stack.ts:17:12 - error TS1128: Declaration or statement expected.

17     public readonly dbUrl: string;
              ~~~~~~~~

../lib/hospital-sys-fargate-stack.ts:18:5 - error TS1128: Declaration or statement expected.

18     public readonly db: rds.DatabaseCluster;
       ~~~~~~

../lib/hospital-sys-fargate-stack.ts:18:12 - error TS1128: Declaration or statement expected.

18     public readonly db: rds.DatabaseCluster;
              ~~~~~~~~

../lib/hospital-sys-fargate-stack.ts:20:22 - error TS1005: ',' expected.

20     constructor(scope: cdk.App, id: string, props: Hospital-sysFargateStackProps) {
                        ~

../lib/hospital-sys-fargate-stack.ts:20:35 - error TS1005: ',' expected.

20     constructor(scope: cdk.App, id: string, props: Hospital-sysFargateStackProps) {
                                     ~

../lib/hospital-sys-fargate-stack.ts:20:50 - error TS1005: ',' expected.

20     constructor(scope: cdk.App, id: string, props: Hospital-sysFargateStackProps) {
                                                    ~

../lib/hospital-sys-fargate-stack.ts:20:83 - error TS1005: ';' expected.

20     constructor(scope: cdk.App, id: string, props: Hospital-sysFargateStackProps) {
                                                                                     ~


Found 22 errors.

```

**Comment by mullermp** [comment]
@chrisgeek I don't know much about typescript, but based on the errors above, I think it has difficulty with names using dashes `Hospital-sysFargateStack`. Try using naming like `HostpitalSys` maybe?

**Comment by chrisgeek** [comment]
@mullermp This is another issue where I implemented your suggestion https://github.com/awslabs/aws-rails-provisioner/issues/20
